apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  sources:

  # Comentat - Helm Chart personalizat pentru Let's Encrypt
  # - repoURL: http://helm-cache.tools/custom
  #   chart: cert-manager
  #   targetRevision: 1.5.3
  #   helm:
  #     releaseName: cert-manager
  #     valueFiles:
  #     - $values/letsencrypt/values.yaml

  # Comentat - Helm Chart Bitnami pentru cert-manager
  - repoURL: https://charts.bitnami.com/bitnami
    chart: cert-manager
    targetRevision: latest
    helm:
     releaseName: cert-manager
     valueFiles:
     - $values/cert-manager/values.yaml

  # ConfigMap și valori pentru Let's Encrypt
  - repoURL: https://github.com/prdmarian/k8s-objects.git  # Repository-ul pentru valori și configurații
    targetRevision: HEAD
    path: cert-manager
    ref: values

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
