apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-cache
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: qualification
  sources:

  # ConfigMap și valori pentru Git Cache
  - repoURL: https://github.com/prdmarian/k8s-objects.git  # Repository-ul pentru valori și configurații
    targetRevision: HEAD
    path: tools/git-cache
    ref: values

  # Comentat - Helm Chart personalizat pentru Git Cache
  # - repoURL: http://helm-cache.tools/custom
  #   chart: git-cache
  #   targetRevision: 1.0.0
  #   helm:
  #     releaseName: git-cache
  #     valueFiles:
  #     - $values/tools/git-cache/values.yaml

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
