apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: web-apps
    server: https://kubernetes.default.svc
  project: qualification
  sources:

  # ConfigMap și valori pentru Web Apps
  - repoURL: https://github.com/prdmarian/k8s-objects.git  # Repository-ul pentru valori și configurații
    targetRevision: HEAD
    path: web-apps
   
