replicaCount: 1

image:
  repository: quay.io/jetstack/cert-manager-controller
  tag: v1.5.3

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 192Mi

readinessProbe:
  exec:
    command:
      - pgrep
      - cainjector
  initialDelaySeconds: 10  # Poți mări această valoare
  timeoutSeconds: 5        # Timeout-ul pentru rularea comenzii
  periodSeconds: 10        # Intervalul la care se va verifica disponibilitatea containerului
  successThreshold: 1
  failureThreshold: 5      # Numărul de eșecuri acceptate înainte de a considera containerul nereușit


# Configurare pentru Cert-Manager pentru a emite certificate SSL
issuer:
  name: letsencrypt-prod
  type: ClusterIssuer
  email: admin@elgg.ro
  server: https://acme-v02.api.letsencrypt.org/directory
  privateKeySecretRef:
    name: letsencrypt-prod
  solvers:
    - http01:
        ingress:
          class: nginx

certificates:
  # Certificate pentru aplicațiile externe (web-apps)
  - name: webapp-cert
    commonName: webapp.elgg.ro
    dnsNames:
      - webapp.elgg.ro
    secretName: webapp-tls
    issuerRef:
      name: letsencrypt-prod
      kind: ClusterIssuer
    dns01:
      provider: cloudflare

  # Certificate pentru aplicațiile interne (grafana, prometheus, ldap, argocd, custom-exporter)
  - name: internal-cert
    commonName: grafana.internal.elgg.ro
    dnsNames:
      - grafana.internal.elgg.ro
      - prometheus.internal.elgg.ro
      - ldap.internal.elgg.ro
      - argocd.internal.elgg.ro
      - custom-exporter.internal.elgg.ro  # Adăugat custom-exporter
    secretName: internal-tls
    issuerRef:
      name: letsencrypt-prod
      kind: ClusterIssuer
    dns01:
      provider: cloudflare
